apiVersion: v1
kind: Namespace
metadata:
  name: v-herd-eu-welcome-page
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: v-herd-eu-welcome-page
spec:
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: v-herd-eu-welcome-page
spec:
  selector:
    app: pod
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: v-herd-eu-welcome-page
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
    - hosts:
        - v-herd.eu
      secretName: v-herd-eu-ingress-tls
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: service
                port:
                  number: 80
