#!/bin/bash
set -e -o pipefail

echo "### Setting up Microk8s"
snap install microk8s --classic
microk8s enable dashboard
microk8s enable dns
microk8s enable registry
microk8s enable ingress:default-ssl-certificate=v-herd-eu-welcome-page/v-herd-eu-ingress-tls
microk8s enable cert-manager
usermod -aG microk8s jenkins

read -p "Create lets-encrypt ClusterIssuer, and press Enter"

microk8s.kbctl apply -f ../welcome-page.yaml

read -p "Please wait until the v-herd.eu certificate has been fetched; then visit https://v-herd.eu"
